version: '2'
services:
  server:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - "mysql"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crash
    volumes:
      - ./database:/var/lib/mysql

  composer:
    image: composer
    volumes:
      - ./examples/mvc:/app
    command: composer install
